//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsolePlantenClient.PlantenService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Plant", Namespace="http://schemas.datacontract.org/2004/07/PlantenServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class Plant : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NaamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrijsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naam {
            get {
                return this.NaamField;
            }
            set {
                if ((object.ReferenceEquals(this.NaamField, value) != true)) {
                    this.NaamField = value;
                    this.RaisePropertyChanged("Naam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Nummer {
            get {
                return this.NummerField;
            }
            set {
                if ((this.NummerField.Equals(value) != true)) {
                    this.NummerField = value;
                    this.RaisePropertyChanged("Nummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Prijs {
            get {
                return this.PrijsField;
            }
            set {
                if ((this.PrijsField.Equals(value) != true)) {
                    this.PrijsField = value;
                    this.RaisePropertyChanged("Prijs");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://vdab.be/plantenservice", ConfigurationName="PlantenService.IPlantenService")]
    public interface IPlantenService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://vdab.be/plantenservice/IPlantenService/GetPlantenVanTotPrijs", ReplyAction="http://vdab.be/plantenservice/IPlantenService/GetPlantenVanTotPrijsResponse")]
        ConsolePlantenClient.PlantenService.Plant[] GetPlantenVanTotPrijs(decimal minPrijs, decimal maxPrijs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://vdab.be/plantenservice/IPlantenService/GetPlantenVanTotPrijs", ReplyAction="http://vdab.be/plantenservice/IPlantenService/GetPlantenVanTotPrijsResponse")]
        System.Threading.Tasks.Task<ConsolePlantenClient.PlantenService.Plant[]> GetPlantenVanTotPrijsAsync(decimal minPrijs, decimal maxPrijs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://vdab.be/plantenservice/IPlantenService/GetPlantenMetWoord", ReplyAction="http://vdab.be/plantenservice/IPlantenService/GetPlantenMetWoordResponse")]
        ConsolePlantenClient.PlantenService.Plant[] GetPlantenMetWoord(string woord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://vdab.be/plantenservice/IPlantenService/GetPlantenMetWoord", ReplyAction="http://vdab.be/plantenservice/IPlantenService/GetPlantenMetWoordResponse")]
        System.Threading.Tasks.Task<ConsolePlantenClient.PlantenService.Plant[]> GetPlantenMetWoordAsync(string woord);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPlantenServiceChannel : ConsolePlantenClient.PlantenService.IPlantenService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlantenServiceClient : System.ServiceModel.ClientBase<ConsolePlantenClient.PlantenService.IPlantenService>, ConsolePlantenClient.PlantenService.IPlantenService {
        
        public PlantenServiceClient() {
        }
        
        public PlantenServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PlantenServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlantenServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlantenServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConsolePlantenClient.PlantenService.Plant[] GetPlantenVanTotPrijs(decimal minPrijs, decimal maxPrijs) {
            return base.Channel.GetPlantenVanTotPrijs(minPrijs, maxPrijs);
        }
        
        public System.Threading.Tasks.Task<ConsolePlantenClient.PlantenService.Plant[]> GetPlantenVanTotPrijsAsync(decimal minPrijs, decimal maxPrijs) {
            return base.Channel.GetPlantenVanTotPrijsAsync(minPrijs, maxPrijs);
        }
        
        public ConsolePlantenClient.PlantenService.Plant[] GetPlantenMetWoord(string woord) {
            return base.Channel.GetPlantenMetWoord(woord);
        }
        
        public System.Threading.Tasks.Task<ConsolePlantenClient.PlantenService.Plant[]> GetPlantenMetWoordAsync(string woord) {
            return base.Channel.GetPlantenMetWoordAsync(woord);
        }
    }
}
